meta-poky: Enable NFS server for linux-yocto-dev
Add the NFS kernel server feature to the linux-yocto-dev configuration
to match the standard linux-yocto setup. This is to fix the OEQA tests
with this error:

- runtime - INFO - test_systemd_failed (systemd.SystemdBasicTests.test_systemd_failed)
- runtime - INFO -  ... FAIL
- runtime - INFO - Traceback (most recent call last):
  File "/lava-downloads/core-image-full-cmdline/meta/lib/oeqa/core/decorator/__init__.py", line 35, in wrapped_f
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lava-downloads/core-image-full-cmdline/meta/lib/oeqa/runtime/cases/systemd.py", line 100, in test_systemd_failed
    output += self.systemctl('status --full --failed')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lava-downloads/core-image-full-cmdline/meta/lib/oeqa/runtime/cases/systemd.py", line 26, in systemctl
    self.assertEqual(status, expected, message)
AssertionError: 3 != 0 : SYSTEMD_BUS_TIMEOUT=240s systemctl status --full --failed
× proc-fs-nfsd.mount - NFSD configuration filesystem
     Loaded: loaded (/usr/lib/systemd/system/proc-fs-nfsd.mount; static)
     Active: failed (Result: exit-code) since Mon 2025-10-13 15:01:58 UTC; 2 months 4 days ago
 Invocation: 14e22af5612e4abaa101f1afcf65a5ce
      Where: /proc/fs/nfsd
       What: nfsd
   Mem peak: 1.2M
        CPU: 32ms
genericarm64 mount[347]: mount: /proc/fs/nfsd: unknown filesystem type 'nfsd'.
genericarm64 mount[347]:        dmesg(1) may have more information after failed mount system call.
genericarm64 systemd[1]: proc-fs-nfsd.mount: Mount process exited, code=exited, status=32/n/a
genericarm64 systemd[1]: proc-fs-nfsd.mount: Failed with result 'exit-code'.
genericarm64 systemd[1]: Failed to mount NFSD configuration filesystem.

Signed-off-by: Javier Tia <javier.tia@linaro.org>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>